substitutions:
  tx_pin: 23
  rx_pin: 33
  project_name: Navien.ATOM-Hub-Switch-D

packages:
  navien: !include navien-esphome-atom-lite-esp32.yml

dashboard_import:
  package_import_url: github://htumanyan/navien/esphome/navien-esphome-atomhub-switch-d.yml
  import_full_config: false

# Physical button on ATOM (GPIO39)
binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: "ATOM Button"
    on_press:
      - button.press: hot_button

# Hot button functionality using Relay 1 (GPIO22)
switch:
  - platform: gpio
    id: hot_button_relay
    pin: 22
    name: "Navien Enable Hot Button"
    restore_mode: RESTORE_DEFAULT_ON
  # Additional relay available for other uses (Relay 2 on GPIO19)
  - platform: gpio
    id: relay_2
    pin: 19
    name: "Relay 2"
    restore_mode: RESTORE_DEFAULT_OFF

button:
  - id: !remove NavienHotButton
  - platform: template
    name: "Hot Button"
    id: hot_button
    on_press:
    - switch.turn_off: hot_button_relay
    - delay: 1000ms
    - switch.turn_on: hot_button_relay
